# Generated by Django 5.2.1 on 2025-05-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='store_customers',
        ),
    ]
