# Generated by Django 5.2.1 on 2025-05-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_first_n_8f83e0_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
    """
    INSERT INTO store_collection(title) VALUES ('collection1')
    """, """
    DELETE FROM store_collection WHERE title='collection1'
    """
        )
    ]
